### ISSUE TITLE
Feature request: Make it possible to store application settings/config near the executable as opposed to user home folder

### ISSUE THREAD

**Issue by user9209** [pgptool/pgptool#157]
Hi,

greate job.
Does a portable mode exist, for example as command line tag
so that the config files a stored at the JAR location and not in the
home folder of the system?

Thanks in Advance

**Comment by skarpushin** [comment]
@user9209, well, PGP Tool can support that scenario, but there is no GUI that will allow you to configure it. Plus you'll need to have JRE either bundled or installed on each system.

If you don't mind some "hacking" (meaning you'll need to pack/unpack files and change some XML), I can give you instructions on how to achieve this effect. 

Let me know.

**Comment by skarpushin** [comment]
@user9209 , ping

**Comment by user9209** [comment]
@skarpushin Thank you very much.
Currently I have not enough time to change or implement a portable mode, so I will use it without portable mode. The portable mode is nice to have but not a  must:

`--datadir data`

**Comment by skarpushin** [comment]
If person who requested this feature does not have enough time to change value in XML, doesn't make sense to me to spend couple days to implementing this.

**Comment by nikant** [comment]
Hello,

if you could elaborate I can make the changes to the files needed. A truly portable version is important..

**Comment by skarpushin** [comment]
@nikant , I've just realized that base path is hard-coded in https://github.com/pgptool/pgptool/blob/c3e8b08bbccce6ccf88b961e5a3af406881153c0/pgptool-gui/src/main/java/org/pgptool/gui/config/impl/ConfigsBasePathResolverUserHomeImpl.java#L42

Hence it doesn't seem to be possible to change it. There is a slim chance though if you set/override environment variable `USERPROFILE`.

I.e. in linux executing following shell command will result in pgp tool using current folder instead of user home
```
USERPROFILE=. java -jar pgptoolgui-0.5.9.2.jar
```
