### ISSUE TITLE
Improvement: Stop adding original extension to encrypted file name

### ISSUE THREAD

**Issue by skarpushin** [pgptool/pgptool#166]
This change is supposed to increase data security, because without knowing file format it's harder to anticipate type of content

**Comment by Steven-M1** [comment]
I like what you did here. 
Initially I was a bit puzzled because the original file extension was not shown before .pgp , yet the decrytion process regenerates it somehow. 
Sometimes I need to decrypt using gpg and I need to manually add the extension after the PGPtool encryption otherwise it will be missing after gpg decryption. 
Good job with the tool!

**Comment by skarpushin** [comment]
hi @Steven-M1, thank you for the feedback!
Can you please clarify -- is it a feature request to make "original extension removal" optional? 
I see that you was puzzled, and I also see that you seem to be satisfied. So I'm not sure -- hence my question above :-)

**Comment by bryrogsum** [comment]
That would be a feature request for me to keep the original file extension after encryption. Sometimes the files I encrypt and send need a specific file extension to be picked up automatically.

Easily worth a couple cups of coffee!

**Comment by Steven-M1** [comment]
Possibly as a user selectable option then?

**Comment by bryrogsum** [comment]
I was thinking of having it as a selectable option (check mark it is on, no check mark it is off) under the "PGPTool" drop-down menu. Since replacing the extension is what most people want, it would make sense to set that as the default setting.
