### ISSUE TITLE
Bulk Encrypt and Decrypt

### ISSUE THREAD

**Issue by ajensen27** [pgptool/pgptool#249]
Is there anything in the works to allow for encrypting or decrypting multiple files at once?

Thanks!

**Comment by skarpushin** [comment]
@ajensen27 , such features planned in future versions. Development pace has slowed down as my personal and professional life got changed a bit, but I'm slowly progressing on the new version anyways. 

I'll close this ticket because it is reflected in future milestones. See:
* https://github.com/pgptool/pgptool/milestone/14
* https://github.com/pgptool/pgptool/milestone/10

**Comment by ajensen27** [comment]
Awesome. Thanks!
