### ISSUE TITLE
Help with secret key lost

### ISSUE THREAD

**Issue by aferrara814** [pgptool/pgptool#250]
Hi, is there a way to recover the pgp private key?

Basically I have installed the pgptool, I generated a pgp key and after some time I have uninstalled the software.

Now reinstalling it I can't find anymore the previously created key, is there a way to recover the private key?

I am using windows 10

**Comment by skarpushin** [comment]
@aferrara814 

- it is not possible to recover key unless you performed a backup copy (same suggested by application right after you create a key pair). 
- Application itself does not send it or store it in alternative locations because this might be perceived as a security concern. 
- If you uninstalled the software but didn't delete `.pgptool` folder and didn't reinstall your user or whole windows, then your private key is still there in you user directory. Please try to open Keyring from the application, you might still find your key there.
