### ISSUE TITLE
my password no longer works!!!

### ISSUE THREAD

**Issue by peskypesky** [pgptool/pgptool#256]
I am irate!!  My password no longer works and I encrypted some files I desperately need access to. This is outrageous.

**Comment by skarpushin** [comment]
@peskypesky I'm sorry to hear that. 

Please note: there is no functionality that could invalidate, block or change your password in a background. Application is simply is not capable of doing this.

The only reason why application does not accepts the password is because password that you enter does not match password that was used to encrypt your secret key. 

Please check 

- that you're using correct keyboard layout (not applicable if you're a native English speaker and do not use other input languages)
- that Caps Lock is in the same position as it was in a time when you've created a key pair

**Comment by peskypesky** [comment]
Hi,
Sorry....but it was my error. I was making one error when I was inputting my passcode. Please accept my apologies.


Paul Escamilla


________________________________

**Comment by skarpushin** [comment]
I'm glad it worked out for you!
