### ISSUE TITLE
Key Disappeared

### ISSUE THREAD

**Issue by Tezos4Life** [pgptool/pgptool#264]
The other day I was generating a new key for 2fa. It actually failed the first 2 times I tried to create the key. It did work the third time and I was able to place my public key on the website and the challenge response all worked fine. When I opened pgptool back up today the key I created was gone. Only the older key was there. Is there a way to recover the key I created the other day?

**Comment by skarpushin** [comment]
@Tezos4Life to answer your question: no, there is no way to recover a key. Keys are not stored in any other locations and are not transmitted over network. I hope you understand why -- for privacy reasons.

And also it is kinda impossible for a key to _disappear_ because it is written on disk as soon as it gets created. So even if you "kill" application using task manager you will not be able make key disappear. You would need to delete it manually or somehow damage `PgpKeysRing` file.

Can you please send me your log file `pgptool-gui.log` to `sergey.v.karpushin@gmail.com` ? It might allow to troubleshoot this case. Please inspect it before sharing and remove all sensitive file names if needed.

**Comment by Tezos4Life** [comment]
sent
