### ISSUE TITLE
How can I verify that someone cannot decrypt with the public key?

### ISSUE THREAD

**Issue by jbowen28** [pgptool/pgptool#279]
I am not confident that your pgptool is secure.
I know that someone who encrypts a message with my public key, should not be able to decrypt without the my private key.

How can I prove that someone cannot decrypt a message encrypted with my public key with just the public key itself (e.g. use the public key as a private key)?

**Comment by skarpushin** [comment]
@jbowen28 you're essentially asking me to give you mathematical proof that OpenPGP encryption works and that BouncyCastle implemented it to correctly. Since PGP Tool does not implement this algorithm itself, but rather uses BouncyCastle library, I suggest you ask same question in BouncyCastle community.

**Comment by jbowen28** [comment]
I am not asking for a mathematical proof but a procedural proof.  Is there a procedure using your app or another OpenPGP app that will take as input a PGP encrypted message encrypted with a given public key and using that same public key allow the user of your app or another OpenPGP app to attempt to decrypt the message?  If your app or another OpenPGP app indicates that the message cannot be decrypted by the public key, then that is sufficient proof as far as I am concerned.

**Comment by skarpushin** [comment]
@jbowen28 I don't have procedural proof for this.

Public and private keys are stored differently and represent different things. I'm not aware of ways to represent public key as private key and then use it to decrypt something. Hypothetically you can try to forge private key from public key binary data, but I never tried it. and I foresee BouncyCastle would just reject such key and complain that key is invalid. 
There is no way to test this in PGP Tool itself because it uses object model when working with encrypting/decrypting, see https://github.com/pgptool/pgptool/blob/0851834eab49b817fda269a614f09c7c2159861c/pgptool-gui/src/main/java/org/pgptool/gui/encryption/implpgp/EncryptionServicePgpImpl.java#L403
