### ISSUE TITLE
Automatic installation window runs on every startup.

### ISSUE THREAD

**Issue by StandingDesk** [pgptool/pgptool#303]
PGPTool runs through a rapid, automatic installation window every time the program is opened. But the program is already installed on my PC. Is this normal behavior, a bug, or a security risk?

Windows 10, Java up to date, PGPTool up to date.

**Comment by skarpushin** [comment]
@StandingDesk sorry for delayed response, I'm on vacation :-)

Honestly I'm not 100% sure what exactly you are talking about... Can you please provide screenshots of what is happening or even better video (screencast) ?
Without knowing what exactly is going on I cannot really answer your question. 

If you're talking about this "Loading..." splash screen, then this is completely normal behavior. 
![image](https://github.com/user-attachments/assets/ba3cca8e-26cf-4738-a48b-4a43713b6f9f)

If you're seeing something else each time running PGP Tool, then yes, this doesn't seem good. 

Also, where did you download PGP Tool?

**Comment by StandingDesk** [comment]
Thanks for your response, and for creating this application. 

Correction on my end: on further testing, I found it's not happening **every** time PGPTool runs, only the first time the program is run after system startup (which makes me wonder if it's prompting another program it's dependent on such a Java to go through an install prompt for startup or something weird like that...but Java is installed on hard drive, loads on startup to my knowledge, fully up to date, not installed as portable app if that is even possible, etc). I tried to capture a screenshot, but the install window happens so quickly I keep missing it. It's definitely a standard windows installer window I'm seeing first (with the blue progress bar moving from left to right), NOT the loading screen (although that appears after). Installed PGPTool through the official site, so it's not malware (https://pgptool.github.io/). 

I feel like I'm going to need to find a better capture solution and dig into event history perhaps to get to the bottom of it. My primary concern is if a program as private as this has been compromised in any way by a bad actor, which in no way I assume is true, or would be you. Just trying to figure out what's going on. 

Apologies for interrupting your vacation. Really grateful for developers like you who make open source programs such as this. I will not be expecting a reply anytime soon given your break, but will update here if I learn more.

**Comment by skarpushin** [comment]
@StandingDesk no problem :-) And yes, https://pgptool.github.io/ is the right place to get application from.

If you can, please do the following:
1. Close PGP Tool
1. Delete file `c:\Users\YOUR_USER_NAME\pgptool-gui.log` (where YOUR_USER_NAME is replaced with the name of your user)
2. Open PGP Tool
3. Close PGP Tool
4. Send me the file `c:\Users\YOUR_USER_NAME\pgptool-gui.log` (review it before sending, it should not contain any sensitive information). You can post it here, or send privately to `sergey.v.karpushin@gmail.com`

Also please send me the screenshot of folder where PGP Tool is installed, like this:
![image](https://github.com/user-attachments/assets/aaa407ac-7aa8-4a4d-9b9d-f70157c3aa79) or even better zip it and send me the contents of this folder for review.

And... Which JRE version do you have and from which provider? Oracle JRE,  Amazon Coretto, Adopt OpenJdk, something else..?

**Comment by StandingDesk** [comment]
Great - followed your instructions and sent you an email with that info you requested for greater confidentiality. 

I have Java from Oracle installed - Version 8, update 421.

**Comment by skarpushin** [comment]
I'm not seeing any abnormalities in the information you've provided. 

Last think I can think of (maybe it should've been the first one :-D) is to check checksums...

I've created SHA512 checksums for both files using Total Commander:
```
84d81ecd140dcd375f850a3af5667b189ebfa0e061c66b8483907d8e6606885a16432f6e5330a2886c08d040b42216510975f609180cd9ce82b624cbc0fd195d *pgptoolgui-0.5.9.3.jar
e5bb484226cf1712926ea3b2ebfdf87efc182e5f0095516662a1c8e019623afbf458436ebaa01021ae41f2679e7895cd1682b8f7be7dc49ed07d7741bcb01d40 *pgptool.exe
```

If you you're using Total Commander too, then it will be super easy to test if files on your machine have same checksums:
1. Download [PGP Tool checksums.txt](https://github.com/user-attachments/files/16569901/PGP.Tool.checksums.txt)
2. Rename extension from `txt` to `sha512`
3. Move it to folder `c:\Program Files (x86)\PGP Tool\`
4. Now using Total Commander do:
   1. Go to folder `c:\Program Files (x86)\PGP Tool\`
   2. Select file `PGP Tool checksums.sha512`
   3. Go to `Files -> Verify Checksums` (this is second last menu item)
   4. Expect to see result "OK" for both files. Like this: 
![image](https://github.com/user-attachments/assets/58c3ef19-e247-4ae5-9091-3abe10848b06)

And you see OK for both files it means that files were not tampered with. 

Next suspect would be a shortcut that you're using to start PGP Tool application... But it is generated by MSI installer for each user individually, so we cannot just verify it using checksum... But there is a way how to check if this has something to do with what you're experiencing...

Instead of starting PGP Tool from start menu or any other shortcut, try starting it by manually double clicking on `pgptool.exe` in `c:\Program Files (x86)\PGP Tool\` folder.

**Comment by StandingDesk** [comment]
You are doing an excellent job on these walk throughs. Total Commander Checksum test showed 0 errors. Opening Pgptool.exe from within Program Files directory ran correctly with no errors. 

The only other thing I can think of is that every time I open PGPTool the Java icon appears in the task bar during the "loading" window, then is immediately replaced by the PGPTool icon in the taskbar. So perhaps sometimes Java is running through some sort of initiation/install process on startup from time to time, for whatever reason, and this has NOTHING to do with PGPTool itself. I have no idea if that's a red flag or not, but that would be a Java issue to hunt down, and not related to this thread. I'm open to any ideas or suggestions on that front if you have any, but otherwise thanks again for your assistance and creating such a convenient way to manage encrypted files.
